language: c
compiler:
  - gcc
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
  packages:
    - check
    - gcc-4.9
    - gettext
    - cmake
before_install:
  - pip install --user cpp-coveralls
  - .ci/install-libcsptr.sh
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/lib
  - export LIBRARY_PATH=$LIBRARY_PATH:$HOME/lib
script:
  - mkdir -p build && cd $_
  - cmake ..
  - make
  - make -C samples test
after_success:
  - coveralls --gcov gcov-4.9 --exclude samples --exclude dependencies --gcov-options '\-lp' -b .
after_failure:
  - cat $(find samples -iname '*.log') /dev/null
