language: c
compiler:
  - gcc
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get -qq update
  - sudo apt-get -qq install -y check gcc-4.9 gettext cmake
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 90
  - sudo pip install cpp-coveralls
  - .ci/install-libcsptr.sh --prefix=/usr
script:
  - mkdir -p build && cd $_ && cmake .. && make && make -C samples test
after_success:
  - coveralls --gcov gcov-4.9 --exclude samples --exclude dependencies --gcov-options '\-lp' -b .
after_failure:
  - cat $(find samples -iname '*.log') /dev/null
