language: c
compiler:
    - gcc-5
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - check
    - gcc-5
    - gettext
    - cmake
before_install:
  - pip install --user cpp-coveralls
  - .ci/install-libcsptr.sh
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/lib
  - export CFLAGS="-g -O0"
script:
  - mkdir -p build && cd $_ && cmake -DCMAKE_PREFIX_PATH=$HOME .. && make && make -C samples test
after_success:
  - coveralls --gcov gcov-4.9 --exclude samples --exclude dependencies --gcov-options '\-lp' -b .
after_failure:
  - cat $(find samples -iname '*.log') /dev/null
