version: 1.3.1_b{build}-{branch}

os: Windows Server 2012

init:
  - git config --global core.autocrlf input
  - 'SET PATH=%PATH%;C:\MinGW\msys\1.0\bin;C:\MinGW\bin;%APPVEYOR_BUILD_FOLDER%\bin;%APPVEYOR_BUILD_FOLDER%\build'

environment:
  COVERALLS_REPO_TOKEN:
    secure: 5nuCg+faxFPeppoNNcSwVobswAVFUf8ut83vw8CX/4W2y0kZkGmwEfCUxSQWiQDU

clone_depth: 5

matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.

platform:
  - x86

configuration: Release

install:
  - 'set GCOV_PREFIX=%APPVEYOR_BUILD_FOLDER%'
  - 'set LOCAL_INSTALL=%APPVEYOR_BUILD_FOLDER%'
  - 'bash -lc "cd $APPVEYOR_BUILD_FOLDER; exec 0</dev/null; .ci/install-libcsptr.sh -G \"MSYS Makefiles\"; true"'
  - 'cd dependencies/libcsptr/build && make && make install && cd ../../../'
  - 'mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=criterion-%APPVEYOR_REPO_TAG_NAME% -DCMAKE_PREFIX_PATH="%LOCAL_INSTALL%" -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug -G "MSYS Makefiles" ..'

build_script:
  - 'make'

test_script:
  - 'make test || bash -lc "cat $APPVEYOR_BUILD_FOLDER/build/Testing/Temporary/LastTest.log"'

after_test:
  - 'make coveralls'

notifications:

  - provider: Email
    to: [franklinmathieu@gmail.com]
    on_build_status_changed: true

after_build:
  - 'make install'
  - 'bash -lc "cd $APPVEYOR_BUILD_FOLDER; exec 0</dev/null; tar -cvjf criterion-${APPVEYOR_REPO_TAG_NAME}-windows-${PLATFORM}.tar.bz2 -C build criterion-${APPVEYOR_REPO_TAG_NAME}"'

artifacts:
  - path: '**\*.tar.bz2'

deploy:
  provider: GitHub
  auth_token:
    secure: MnZZQeoxBVnpV9GSSvVok5Je0/N2d/fzG4+ITw95/tYSgZ8rleBV23a5sCwAea3r
  artifact: 'criterion-$(APPVEYOR_REPO_TAG_NAME)-windows-$(PLATFORM).tar.bz2'
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
