version: 0.3.0.{build}-{branch}

os: Windows Server 2012

init:
  - ps: (New-Object System.Net.WebClient).DownloadFile("https://cygwin.com/setup-x86.exe", "c:\setup-x86.exe")
  - git config --global core.autocrlf input
  - c:\setup-x86.exe -qnNdO -R C:/cygwin -s http://cygwin.mirror.constant.com -l C:/cygwin/var/cache/setup \
    -P autoconf \
    -P automake \
    -P gcc-core \
    -P mingw-runtime \
    -P mingw-binutils \
    -P mingw-gcc-core \
    -P mingw-pthreads \
    -P mingw-w32api \
    -P libtool \
    -P make \
    -P python \
    -P gettext-devel \
    -P gettext \
    -P expat \
    -P intltool \
    -P libiconv \
    -P pkg-config \
    -P check \
    -P git \
    -P wget \
    -P curl

clone_depth: 5

matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.

platform:
  - x86
  - Any CPU

configuration: Release

install:
  - cmd: c:\cygwin\bin\bash -c './autogen.sh && ./configure'

build_script:
  - cmd: c:\cygwin\bin\bash -c 'make'

test_script:
  - cmd: c:\cygwin\bin\bash -c 'make check'

notifications:

  - provider: Email
    to: [franklinmathieu@gmail.com]
    on_build_status_changed: true
