version: 1.3.1_b{build}-{branch}

os: Visual Studio 2015

init:
  - git config --global core.autocrlf input
  - 'SET PATH=C:\MinGW\bin;%PATH%;C:\MinGW\msys\1.0\bin;%APPVEYOR_BUILD_FOLDER%\build'

environment:
  COVERALLS_REPO_TOKEN:
    secure: 5nuCg+faxFPeppoNNcSwVobswAVFUf8ut83vw8CX/4W2y0kZkGmwEfCUxSQWiQDU
  CI_NAME: appveyor
  CI_JOB_ID: $(APPVEYOR_JOB_ID)
  LOCAL_INSTALL: $(APPVEYOR_BUILD_FOLDER)
  GCOV_PREFIX: $(APPVEYOR_BUILD_FOLDER)
  matrix:
  - COMPILER: mingw
    GENERATOR: "MSYS Makefiles"
  - COMPILER: msvc
    GENERATOR: "Visual Studio 14 2015"

clone_depth: 5

platform:
  - x86_64

configuration: Release

install:
  # Hack to make git think it is on the tip of the repo branch
  - 'git checkout -B %APPVEYOR_REPO_BRANCH%'
  # Configure project
  - 'mkdir build && cd build'
  - >
      cmake
      -Wno-dev
      -DCMAKE_INSTALL_PREFIX="criterion-%APPVEYOR_REPO_TAG_NAME%"
      -DCMAKE_PREFIX_PATH="%LOCAL_INSTALL%"
      -G "%GENERATOR%"
      ..

build_script:
  - cmake --build .
  - ps: |
        # HACK: We need to copy criterion.dll into the binary directory
        if ($env:Compiler -eq "msvc") {
            Copy-Item Debug/criterion.dll samples/Debug/
            Copy-Item Debug/criterion.dll test/Debug/
        }

before_deploy:
  - ps: |
        if ($env:Compiler -eq "mingw" -and !$env:APPVEYOR_REPO_TAG_NAME) {
            cmake --build . --target install
            7z a -ttar "criterion-$env:APPVEYOR_REPO_BRANCH-windows-$env:PLATFORM.tar" "criterion-$env:APPVEYOR_REPO_TAG_NAME"
            7z a -tbzip2 "../criterion-$env:APPVEYOR_REPO_TAG_NAME-windows-$env:PLATFORM.tar.bz2" "criterion-$env:APPVEYOR_REPO_TAG_NAME-windows-$env:PLATFORM.tar"
            Push-AppveyorArtifact "../criterion-$env:APPVEYOR_REPO_TAG_NAME-windows-$env:PLATFORM.tar.bz2"
        }

test_script:
  - ps: try { ctest } catch { type Testing/Temporary/LastTest.log }

#after_test:
#  - 'make coveralls'

notifications:

  - provider: Email
    to: [franklinmathieu@gmail.com]
    on_build_status_changed: true

deploy:
  provider: GitHub
  auth_token:
    secure: MnZZQeoxBVnpV9GSSvVok5Je0/N2d/fzG4+ITw95/tYSgZ8rleBV23a5sCwAea3r
  artifact: 'criterion-$(APPVEYOR_REPO_TAG_NAME)-windows-$(PLATFORM).tar.bz2'
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
