version: 1.2.3_b{build}-{branch}

os: Windows Server 2012

init:
  - git config --global core.autocrlf input
  - C:\MinGW\bin\mingw-get install mingw32-autotools curl
  - 'SET PATH=%PATH%;C:\MinGW\msys\1.0\bin;C:\MinGW\bin'

environment:
  COVERALLS_TOKEN:
    secure: 5nuCg+faxFPeppoNNcSwVobswAVFUf8ut83vw8CX/4W2y0kZkGmwEfCUxSQWiQDU

clone_depth: 5

matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.

platform:
  - x86

configuration: Release

install:
  - 'set GCOV_PREFIX=%APPVEYOR_BUILD_FOLDER%'
  - 'bash -lc "cd $APPVEYOR_BUILD_FOLDER; exec 0</dev/null; .ci/install-libcsptr.sh --host i686-w64-mingw32"'
  - 'mkdir build & cd build'
  - 'cmake -DCMAKE_PREFIX_PATH=%HOME% -G "MSYS Makefiles" ..'

build_script:
  - 'mingw32-make'

test_script:
  - 'mingw32-make test'

after_test:
  - '%CYG_BASH% -lc "cat $(find $APPVEYOR_BUILD_FOLDER/samples -iname \"*.log\") /dev/null'
  - 'mingw32-make coveralls'

notifications:

  - provider: Email
    to: [franklinmathieu@gmail.com]
    on_build_status_changed: true
