version: 1.2.3_b{build}-{branch}

os: Windows Server 2012

init:
  - git config --global core.autocrlf input
  - 'SET PATH=%PATH%;C:\MinGW\msys\1.0\bin;C:\MinGW\bin;%APPVEYOR_BUILD_FOLDER%\bin'

environment:
  COVERALLS_TOKEN:
    secure: 5nuCg+faxFPeppoNNcSwVobswAVFUf8ut83vw8CX/4W2y0kZkGmwEfCUxSQWiQDU

clone_depth: 5

matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.

platform:
  - x86

configuration: Release

install:
  - 'set GCOV_PREFIX=%APPVEYOR_BUILD_FOLDER%'
  - 'set LOCAL_INSTALL=%APPVEYOR_BUILD_FOLDER%'
  - 'bash -lc "cd $APPVEYOR_BUILD_FOLDER; exec 0</dev/null; .ci/install-libcsptr.sh -G \"MSYS Makefiles\"; true"'
  - 'cd dependencies/libcsptr/build && make && make install && cd ../../../'
  - 'mkdir build && cd build && cmake -DCMAKE_PREFIX_PATH="%LOCAL_INSTALL%" -G "MSYS Makefiles" ..'

build_script:
  - 'make'

test_script:
  - 'make test || bash -lc "cat $APPVEYOR_BUILD_FOLDER/build/Testing/Temporary/LastTest.log"'

after_test:
  - 'make coveralls'

notifications:

  - provider: Email
    to: [franklinmathieu@gmail.com]
    on_build_status_changed: true
